title: lkiesow::weblog
description: >
   Random notes from
   a security-aware software engineer,
   open-source advocate
   and occasional lecturer.
theme: jekyll-theme-midnight
show_downloads: false
